apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: apizarro
spec:
  host: apizarro.apps.ocp.ar.
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: apizarro
    weight: 100
  wildcardPolicy: None
