apiVersion: v1
kind: Service
metadata:
  name: apizarro
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    deploymentConfig: apizarro
  sessionAffinity: None
  type: ClusterIP